module.exports = {
  CATEGORIES: [
    "Food & Dining",
    "Transport",
    "Shopping",
    "Rent & Housing",
    "Health",
    "Entertainment",
    "Utilities",
    "Education",
    "Travel",
    "Fitness",
    "Groceries",
    "Subscriptions",
    "Personal Care",
    "Investments",
    "Gifts & Charity",
    "Other",
  ],
  ITEMS_PER_PAGE: 10,
  MAX_LOGIN_ATTEMPTS: 5,
  RATE_LIMIT_WINDOW_MS: 15 * 60 * 1000,
  RATE_LIMIT_MAX: 100,
};